#!/usr/bin/env bash
#PBS -q omp
#PBS -l ncpus=10
#PBS -l mem=10gb
#PBS -l walltime=10:10:00



CB_NAME=$(basename $PBS_JOBNAME)
CB_TIMESTAMP=$(date +%Y-%m-%d_%Hh%Mm%Ss)
CB_LOG_FOLDER=$DATAWORK/"$CB_TIMESTAMP"_"$CB_NAME"
mkdir -p $CB_LOG_FOLDER
cp $0 $CB_LOG_FOLDER/$CB_NAME

# Activation de l'environnement BLAST+ 2.6.0
. /appli/bioinfo/blast/2.6.0/env.sh

cd $PBS_O_WORKDIR

QUERY=$DATAWORK/centile_5.fasta

BANK=/home/ref-bioinfo/beedeem/p/Uniprot_SwissProt/current/Uniprot_SwissProt/Uniprot_SwissProtM


OUT_FILE=Swissprot_annotation.txt

BLAST_PARAM="-evalue 1e-4"



blastx -query "${QUERY}" -db "${BANK}" -out ${OUT_FILE} -max_target_seqs 1 -maxhsps 1 ${BLAST_PARAM} -num_threads 10 -outfmt "6 qseqid salltitles sallacc pident length sblastnames evalue bitscore sseqid " 2>&1 | tee $SCRATCH/98_log_files/"$TIMESTAMP"_swiss_100.log
